POST http://localhost:3333/register
Content-Type: application/json

{
  "nome": "mike",
  "password": "123123",
  "email": "rodri.midas@gmail.com",
  "numero": "123123123",
  "morada": "lisboa 123 123"

}
###

GET http://localhost:3333/user
Content-Type: application/json

###

POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "rodri.midas@gmail.com",
  "password": "123123"
}
###
GET http://localhost:3333/usercheck
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6Im1pa2UiLCJlbWFpbCI6InJvZHJpLm1pZGFzQGdtYWlsLmNvbSIsIm51bWVybyI6IjEyMzEyMzEyMyIsIm1vcmFkYSI6Imxpc2JvYSAxMjMgMTIzIiwiaWF0IjoxNjgzMTQ2NjY4fQ.q0v24iCa1o1wUbvr080zoo-SB15rbgIgWRZ16MzJjKY
###

PUT http://localhost:3333/user
Content-Type: application/json

{
  "id": 9,
  "perm_id":2,
  "nome": "Rodrigo",
  "password": "123123",
  "email": "rodri.midas@gmail.com",
  "numero": "123123123",
  "morada": "lisboa 123 123"

}
###
POST http://localhost:3333/createreserva
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwibm9tZSI6Ik1pZ3VlbCBBbG1laWRhIiwiZW1haWwiOiJ4cHRvczMyNEBnbWFpbC5jb20iLCJudW1lcm8iOiI5MzYyNzQ2ODEiLCJtb3JhZGEiOiJFc3RyYWRhIGRvcyBBbGFtb3MsIFByw6lkaW8gMjEsIDPCukMiLCJwZXJtIjozLCJpYXQiOjE2ODM0MDI5NDN9.vz_0xY_Urvs7EuBCx_otr1dxN3bvXY-Yd1hrO4Uhk5o

{
  "restaurante_id": 1,
  "reserva_data": "05/02/2023",
  "reserva_hora": 12
}
###
GET http://localhost:3333/reserva

{
  "restaurante_id": 1,
  "reserva_data": "05/02/2023",
  "reserva_hora": 12
}
###
GET http://localhost:3333/reserva